### ISSUE TITLE
  Remove logback core from main dependencies

### ISSUE THREAD

**Issue by chibenwa** [yahoo/imapnio#145]
## Description

```
java.lang.NoSuchMethodError: 'java.lang.String ch.qos.logback.core.util.EnvUtil.logbackVersion()'

	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:81)
	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:77)
	at ch.qos.logback.classic.spi.LogbackServiceProvider.initializeLoggerContext(LogbackServiceProvider.java:50)
	at ch.qos.logback.classic.spi.LogbackServiceProvider.initialize(LogbackServiceProvider.java:41)
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:183)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:170)
	at org.slf4j.LoggerFactory.getProvider(LoggerFactory.java:455)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:441)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:390)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:416)
	at org.apache.james.mock.smtp.server.testing.MockSmtpServerExtension$DockerMockSmtp.<clinit>(MockSmtpServerExtension.java:43)
	at org.apache.james.mock.smtp.server.testing.MockSmtpServerExtension.<init>(MockSmtpServerExtension.java:77)
	at org.apache.james.mailets.RemoteDeliveryForwardIntegrationTest.<clinit>(RemoteDeliveryForwardIntegrationTest.java:76)
```

Clashes on versions of logback core.

IMO there's no rationals for forcing this: SLF4J logging facade is plenty enough...

## Expected Behavior
Remove `logback-core` + `logback-classic` dependencies, keep them as testing dependencies.

## Actual Behavior

Included and not compatible with those I have on James side.

I need to do exclusions: that's ugly...

```
        <dependency>
            <groupId>com.yahoo.smtpnio</groupId>
            <artifactId>imapnio.core</artifactId>
            <version>1.1.0</version>
            <exclusions>
                <exclusion>
                    <groupId>ch.qos.logback</groupId>
                    <artifactId>logback-classic</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>ch.qos.logback</groupId>
                    <artifactId>logback-core</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

## Possible Fix

Remove `logback-core` + `logback-classic` dependencies, keep them as testing dependencies.

**Comment by nvsnvikram** [comment]
this was completed.
